---
- name: Install nginx
  ansible.builtin.apt:
    update_cache: true
    name: nginx
    state: present
- name: Copy nginx config from template
  ansible.builtin.template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/conf.d/site-{{ item }}.conf'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
  notify: restart nginx
- name: Create sites folders
  ansible.builtin.file:
    path: '/var/www/{{ item }}/'
    state: directory
    owner: root
    group: root
    mode: '0755'  # rwxr-xr-x
  loop: '{{ sites }}'
- name: Copy index from template
  ansible.builtin.template:
    src: 'index.html.j2'
    dest: '/var/www/{{ item }}/index.html'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
